name: Feature Request
description: Propose a new feature or enhancement.
title: "feat: short description"
labels: ["type: feature", "status: triage"]
body:
  - type: markdown
    attributes:
      value: |
        Describe the problem you're trying to solve and your proposed solution.
        Focus on the *what* and *why* — implementation details can come later.

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem does this feature solve? Why is the current behavior insufficient?
      placeholder: "Describe the pain point or unmet need."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How should this work? Include CLI examples, API sketches, or UI mockups.
      placeholder: |
        forge-terrain export --format godot --chunked
        # Exports terrain as Godot-compatible chunked tilemap
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      description: How do we know this is done? Be specific.
      placeholder: |
        - [ ] CLI command accepts --format flag
        - [ ] Output validates against export schema
        - [ ] Tests cover happy path and error cases

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - Nice to have — not blocking anything
        - Important — needed for upcoming work
        - Blocking — cannot proceed without this
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: What other approaches did you consider? Why were they rejected?

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Related issues, prior art, screenshots, etc.

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues and this has not been requested
          required: true
        - label: I described the problem, not just the solution
          required: true
